// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALB0l0l-D8rwGbENSzhPQS5lnVL8xPV6M',
    appId: '1:417703451528:web:832dd55fcf63f89980383d',
    messagingSenderId: '417703451528',
    projectId: 'blockchain-voting-system-6f8e9',
    authDomain: 'blockchain-voting-system-6f8e9.firebaseapp.com',
    storageBucket: 'blockchain-voting-system-6f8e9.firebasestorage.app',
    measurementId: 'G-V1F3Q8MG2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNj1tsrLdIoVfzG8Ju6Pd910FvKJISsRM',
    appId: '1:417703451528:android:5306b8eaa4015c8880383d',
    messagingSenderId: '417703451528',
    projectId: 'blockchain-voting-system-6f8e9',
    storageBucket: 'blockchain-voting-system-6f8e9.firebasestorage.app',
  );
}
